# TODO: Manage resources to each service
services:
  api-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ":9999"
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - API_ID=1
      - DATABASE_URL=data/app.db
    volumes:
      - shared_db:/data

  api-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ":9999"
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - API_ID=2
      - DATABASE_URL=data/app.db
    volumes:
      - shared_db:/data

  load_balancer:
    image: nginx:latest
    ports:
      - "9999:80"
    depends_on:
      - api-1
      - api-2
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  shared_db:
    driver: local
