services:
  api-1: &api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ":9999"
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - NUM_WORKERS=5
      - DATABASE_URL=data/app_db
    volumes:
      - shared_db:/data
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: 135M
  api-2:
    <<: *api
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - NUM_WORKERS=5
      - DATABASE_URL=data/app_db

  load_balancer:
    image: nginx:latest
    ports:
      - "9999:80"
    depends_on:
      - api-1
      - api-2
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 80M

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  shared_db:
    driver: local
