services:
  api-1: &api
    build:
      context: .
      dockerfile: api/Dockerfile
    networks:
      - payment-processor
    depends_on:
      - rinha-db
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - NUM_WORKERS=10
      - API_PATH=/tmp/api-1.sock
    volumes:
      - ipc-socket:/tmp
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: 165M
  api-2:
    <<: *api
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - NUM_WORKERS=10
      - API_PATH=/tmp/api-2.sock

  rinha-db:
    build:
      context: .
      dockerfile: rinha-db/Dockerfile
    volumes:
      - ipc-socket:/tmp

  load_balancer:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "9999:9999"
    depends_on:
      - api-1
      - rinha-db
    volumes:
      - ipc-socket:/tmp
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 20M

networks:
  payment-processor:
    external: true

volumes:
  ipc-socket:
